apiVersion: v1
appVersion: "1.0"
description: A bridge connecting Kibana to Kusto (Azure Data Explorer) as its backend database
name: k2bridge
version: 0.5.0
dependencies:
  - name: elasticsearch
    version: ~7.16.2
    repository: "@elastic"
    tags:
      - k2bridge-internal-elasticsearch
